version: "2"
services:
  devel:
    image: eeacms/www-devel
    volumes:
    - ./versions.cfg:/plone/instance/versions.cfg
    - ./.gitconfig:/root/.gitconfig:ro
    - ./.pypirc:/root/.pypirc:ro
    - ./.mkrelease:/root/.mkrelease:ro
    - ./.ssh:/root/.ssh
    stdin_open: true
    tty: true
    environment:
      GIT_BRANCH: "master"
    command:
    - "/debug.sh"
